#!/usr/bin/perl -w
# Copyright (C) 2012 Intel Corporation
# Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

use FindBin;
use lib $FindBin::Bin;
use Getopt::Long qw(:config pass_through no_auto_abbrev);
use webkitdirs;

use constant WEBRTC_VERSION => 4804;
my $showHelp = 0;
my $useWebrtc = 0;

my $programName = basename($0);
my $usage = <<EOF;
Usage: $programName [options]
  --help                            Show this help message

  --[no-]webrtc                     Enable/Disable building webrtc libraries (default: enabled).

EOF

%options = (
    "help" => \$showHelp,
    "webrtc!" => \$useWebrtc,
);

GetOptions(%options);

if ($showHelp) {
    print STDERR $usage;
    exit 1;
}

my $scriptsDir = relativeScriptsDir();
system("perl", "$scriptsDir/update-webkit-libs-jhbuild", "--nix") == 0 or die $!;

if (!$useWebrtc) {
    print "Building webrtc libraries are disabled.\n";
    exit 0;
}

print "Started checkout of webrtc libraries and dependencies.\n";

# jhbuild doesn't support exotic things used by libwebrtc
# so we try to do all the stuff with our own bare hands
my $originalCwd = getcwd();
my $sourcePath = getJhbuildPath().'/Source';

my $depotToolsDir = "$sourcePath/depot_tools";
my $depotToolsUrl = "https://chromium.googlesource.com/chromium/tools/depot_tools.git";

if (-d $depotToolsDir) {
    chdir $depotToolsDir;
    system("git pull origin master");
    chdir $originalCwd;
} else {
    system("git clone $depotToolsUrl $depotToolsDir") == 0 or die $!
}

my $webRTCDir = "$sourcePath/webrtc";
File::Path::mkpath($webRTCDir) if (not -d $webRTCDir);
chdir $webRTCDir;
system("$depotToolsDir/gclient config http://webrtc.googlecode.com/svn/trunk") == 0 or die $!;
system("$depotToolsDir/gclient sync --revision ${\WEBRTC_VERSION} --force") == 0 or die $!;

my $toolsDir = "$originalCwd/$scriptsDir/..";
chdir "trunk" or die $!;
print "Started building the webrtc libraries.\n";
system("python build/gyp_chromium --depth=. -Dextra_gyp_flag=0 -Dinclude_tests=0 -Denable_google_now=0 -Dlogging=0 all.gyp") == 0 or die $!;
system("patch -f -r - --no-backup-if-mismatch -p0 -i $toolsDir/nix/patches/fix_jnipeerconnection.patch");
system("$depotToolsDir/ninja -C out/Release") == 0 or die $!;
