list(APPEND JSC_LIBRARIES
    ${GLIB_LIBRARIES}
    ${CMAKE_DL_LIBS}
)

if (APPLE)
list(APPEND JSC_LIBRARIES
    ${READLINE_LIBRARY}
    ${CARBON_LIBRARY}
    ${APPKIT_LIBRARY}
    ${IOKIT_LIBRARY}
)
endif()
